version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
    labels:
      - area/dependencies
    ignore:
      - dependency-name: com.google.protobuf:protoc
