name: Build

on:
  workflow_call:
    inputs:
      javaVersion:
        required: true
        type: string
      etcdImage:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set Up Java'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: 'Build Project'
        env:
          ETCD_IMAGE: ${{ inputs.etcdImage }}
        run: |
          export TC_USER="$(id -u):$(id -g)"
          echo "tc user -> $TC_USER"

          ./gradlew test --info
