name: Checks

on:
  workflow_call:


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: 'Set Up Java'
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: 'Run check task'
        run: |
          ./gradlew check -x test
      - name: 'Run check script'
        run: |
          bash ./.github/workflows/scripts/precheck.sh
        shell: bash

  deps:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
